import type React from "react";

export const C = {
  bg: "#080808",
  bgCard: "#0f0f0f",
  bgModal: "#0d0d0d",
  bgInput: "#080808",
  border: "#1a1a1a",
  borderHover: "#2a2a2a",
  borderAccentRed: "rgba(220,38,38,0.35)",
  borderAccentOrange: "rgba(249,115,22,0.3)",
  primary: "#f97316",
  primaryDark: "#ea580c",
  danger: "#dc2626",
  gradient: "linear-gradient(135deg,#dc2626,#ea580c)",
  text: "#ffffff",
  textSub: "#888888",
  textMuted: "#444444",
  activeGreen: "#22c55e",
  glassBg: "rgba(255,255,255,0.04)",
  glassBorder: "rgba(255,255,255,0.08)",
  glassBorderSelected: "rgba(249,115,22,0.3)",
  glowOrange: "rgba(249,115,22,0.1)",
} as const;

export const S: Record<string, React.CSSProperties> = {
  card: {
    background: C.bgCard,
    border: `1px solid ${C.border}`,
    borderRadius: "8px",
    padding: "16px",
  },
  cardAccent: {
    background: C.bgCard,
    border: `1px solid ${C.borderAccentRed}`,
    borderRadius: "8px",
    padding: "16px",
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: "6px",
    border: `1px solid ${C.border}`,
    background: C.bgInput,
    color: C.text,
    outline: "none",
    fontSize: "14px",
    boxSizing: "border-box",
  },
  primaryBtn: {
    background: C.gradient,
    color: "white",
    border: "none",
    borderRadius: "5px",
    padding: "8px 16px",
    cursor: "pointer",
    fontWeight: 700,
    fontSize: "13px",
  },
  secondaryBtn: {
    background: "transparent",
    color: C.textSub,
    border: `1px solid ${C.border}`,
    borderRadius: "5px",
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: "13px",
  },
  dangerBtn: {
    background: "transparent",
    color: C.danger,
    border: `1px solid rgba(220,38,38,0.4)`,
    borderRadius: "5px",
    padding: "8px 16px",
    cursor: "pointer",
    fontSize: "13px",
  },
  label: {
    color: C.textMuted,
    fontSize: "9px",
    textTransform: "uppercase",
    letterSpacing: "2px",
  } as React.CSSProperties,
  statValue: {
    color: C.primary,
    fontSize: "20px",
    fontWeight: 800,
  },
  sectionTitle: {
    color: C.text,
    fontSize: "18px",
    fontWeight: 800,
    marginBottom: "12px",
  },
};
