// <auto-generated />
using System;
using Api.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.DataBase.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260309195340_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Aircrafts.Domain.Aircraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MaxPassengers")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ScenarioConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("TailNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WakeCategory")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioConfigId");

                    b.ToTable("aircrafts", (string)null);
                });

            modelBuilder.Entity("Modules.Airports.Domain.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("StandCapacity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("airports", (string)null);
                });

            modelBuilder.Entity("Modules.Airports.Domain.Runway", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AirportId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RunwayType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("runways", (string)null);
                });

            modelBuilder.Entity("Modules.Login.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Modules.Scenarios.Domain.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AircraftId")
                        .HasColumnType("uuid");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("MaxDelayMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxEarlyMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("ScenarioConfigId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AircraftId");

                    b.HasIndex("ScenarioConfigId");

                    b.HasIndex("ScenarioConfigId", "Callsign")
                        .IsUnique();

                    b.ToTable("flights", (string)null);
                });

            modelBuilder.Entity("Modules.Scenarios.Domain.ScenarioConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AircraftCount")
                        .HasColumnType("integer");

                    b.Property<int>("AircraftDifficulty")
                        .HasColumnType("integer");

                    b.Property<Guid>("AirportId")
                        .HasColumnType("uuid");

                    b.Property<int>("BaseSeparationSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("Difficulty")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InboundAircraftCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinWeatherIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OnGroundAircraftCount")
                        .HasColumnType("integer");

                    b.Property<int>("RemainingOnGroundAircraftCount")
                        .HasColumnType("integer");

                    b.Property<int>("Seed")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WakePercent")
                        .HasColumnType("integer");

                    b.Property<int>("WeatherDifficulty")
                        .HasColumnType("integer");

                    b.Property<int>("WeatherIntervalCount")
                        .HasColumnType("integer");

                    b.Property<int>("WeatherPercent")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.ToTable("scenario_configs", (string)null);
                });

            modelBuilder.Entity("Modules.Scenarios.Domain.WeatherInterval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScenarioConfigId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WeatherType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioConfigId");

                    b.ToTable("weather_intervals", (string)null);
                });

            modelBuilder.Entity("Modules.Aircrafts.Domain.Aircraft", b =>
                {
                    b.HasOne("Modules.Scenarios.Domain.ScenarioConfig", null)
                        .WithMany("Aircrafts")
                        .HasForeignKey("ScenarioConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Airports.Domain.Runway", b =>
                {
                    b.HasOne("Modules.Airports.Domain.Airport", null)
                        .WithMany()
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Scenarios.Domain.Flight", b =>
                {
                    b.HasOne("Modules.Aircrafts.Domain.Aircraft", null)
                        .WithMany()
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Modules.Scenarios.Domain.ScenarioConfig", null)
                        .WithMany("Flights")
                        .HasForeignKey("ScenarioConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Scenarios.Domain.ScenarioConfig", b =>
                {
                    b.HasOne("Modules.Airports.Domain.Airport", null)
                        .WithMany()
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Scenarios.Domain.WeatherInterval", b =>
                {
                    b.HasOne("Modules.Scenarios.Domain.ScenarioConfig", null)
                        .WithMany("WeatherIntervals")
                        .HasForeignKey("ScenarioConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Scenarios.Domain.ScenarioConfig", b =>
                {
                    b.Navigation("Aircrafts");

                    b.Navigation("Flights");

                    b.Navigation("WeatherIntervals");
                });
#pragma warning restore 612, 618
        }
    }
}
